### ISSUE TITLE
Mechanism for locking league

### ISSUE THREAD

**Issue by bendemboski** [leaguevine/fantasy-ultimate#4]
At some point we are going to lock the league and allow no further team creation. We need to figure out exactly what this means -- what UI we show/hide before and after this happens. We also might want to indicate when the league is going to be locked somewhere so people know how long they  have.

**Comment by mliu7** [comment]
I think this can be really simple. 

Before the league is locked, on the My Team page where you can create or edit your team, add a line that says "You can modify your team anytime before [date/time]".

After the league is locked, if the user already has a team, the My Team page can say "This league's scoring has officially started so you can no longer modify your team."

After the league is locked, if the user doesn't have a team yet, the My Team page can say "This league's scoring has officially started so you cannot create a new team."
